from time import sleep

print("          i 											i				")
sleep(1)
print("        i i i 									   iiii				")
sleep(1)
print("      i i i i i 										i				")
sleep(1)    
print("    -------------")
sleep(1)
print("   |_^_^_^_^_^_^_|")
sleep(1)
print("   |_*_*_*_*_*_*_|")
sleep(1)
print("   /-------------\\")
sleep(1)
print("   |:-:-:-:-:-:-:|")
sleep(1)
print("   |*-*-*-*-*-*-*|")
sleep(1)
print("   i-------------i")
sleep(1)
print("---------------------")
print("\n  ++++++++++++++++")
sleep(1)
print("  +Happy Birthday+")
sleep(1)
print("  ++++++++++++++++")
sleep(1)
print("  >             <")
sleep(1)
print("  May God Bless You ;)")
sleep(1)

